# Base/default settings
app:
  name: Casino Intervention API
  version: V10

log:
  level: INFO
  disable_existing_loggers: false

cors_allow_origins:
  - http://localhost:3000
  - http://127.0.0.1:3000

data:
  dir: data
  alerts_csv_name: predictive_fill_top_alerts_v10.csv
  ack_file_name: acknowledged_alerts_v10.csv

pas:
  base_url: https://YOUR-PAS-ENDPOINT
  partner_id: your-partner-id
  api_key: your-api-key
  decision_topic: inspection-decisions

