model_registry:
  postgres:
    replica_url: postgresql+psycopg://wdts_admin:fot_wdtsf07@172.19.10.8:5432/wdts_reportdb?options=-c%20search_path%3Dwdts_reporting

  kafka:
    bootstrap_servers: localhost:9092
    client_id: cortex-models
    acks: all

  models:
    predicted_fills:
      enabled: true
      parameters:
        end_ts: 2026-05-10 12-00-00 # now or %Y-%m-%d_%H-%M-%S
        json_limit: 3    

